use_frameworks!

target 'HTMIWork_Example' do
  pod 'HTMIWork', :path => '../'
  pod'AFNetworking', '~> 3.1.0'

  target 'HTMIWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
