source 'https://git.coding.net/MyCoding521/HTMIWork.git'
source 'https://git.coding.net/MyCoding521/HTMINetWork.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HTMIWork_Example' do
  pod 'HTMIWork', :path => '../'
  pod'AFNetworking', '~> 3.1.0'
  pod 'HTMINetWork', '~> 1.1.4'
#  pod 'HTMIWork', '~> 0.1.3'

  target 'HTMIWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
